### ISSUE TITLE
yoda

### ISSUE THREAD

**Issue by SunRise-ppl** [TheRealToxicDev/Ninja-Bot-Source#2]
yoda be dead

**Comment by CodeMeAPixel** [comment]
# Update
• Snekfetch is Deprecated use `node-fetch`

• Yoda Command is Semi Working

**Comment by CodeMeAPixel** [comment]
Replace contents of Yoda Command file with the code below 


const Discord = require("discord.js");
const bot = new Discord.Client();
const snek = require('node-fetch');

exports.run = async (client, message, args) => {

const speech = args.join(' ');

if (speech.length < 2) return message.channel.send(`${message.author.username} You must supply text for Yoda. Yes.`);

const text = await snek(`http://yoda-api.appspot.com/api/v1/yodish?text=${encodeURIComponent(speech.toLowerCase())}`)

.then(res => res.text()) // expecting a json response
.then(body => {
message.channel.send(JSON.parse(body).yodish).catch(console.error);
});
}


for a semi working command 👌 will update with more fixes.
